<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $this->translate('Oldtimers') ?></title>

    <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.mobile.custom.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
    <?php //echo $this->content; ?>
        <div class="row">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" href="<?php echo $this->url('home') ?>"></a>
                    </div>
                    
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <div>
                        <form method="post" action="" id="searchForm" class="form-inline">
                          <div class="form-group">
                            <select class="form-control" name="brand" id="brand">
                                <option>Brand</option>
                                <option>Mercedes</option>
                                <option>BMW</option>
                                <option>Toyota</option>
                                <option>Volkswagen</option>
                            </select>
                          </div>
                          <div class="form-group">
                            <select class="form-control" name="model" id="model">
                                <option>Model</option>
                                <option>W202</option>
                                <option>E124</option>
                                <option>W220</option>
                                <option>SLK</option>
                            </select>
                          </div>
                          <div class="form-group">
                            <select class="form-control" name="priceBetween" id="priceBetween">
                                <option>500-1000€</option>
                                <option>1000-2000€</option>
                                <option>2000-3000€</option>
                                <option>3000-5000€</option>
                            </select>
                          </div>
                          <div class="form-group">
                            <select class="form-control" name="yearFrom" id="yearFrom">
                                <option>1990</option>
                                <option>1995</option>
                                <option>2000</option>
                                <option>2005</option>
                            </select>
                          </div>
                          <div class="form-group">
                            <select class="form-control" name="fuel" id="fuel">
                                <option>Diesel</option>
                                <option>Petrol</option>
                                <option>Petrol/Gas</option>
                            </select>
                          </div>
                          <div class="form-group">
                            <button type="submit" class="btn btn-default" id="search" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">Search</button>
                          </div>
                        </form>
                    </div>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic1" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/111.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Volkswagen | Transporter T5 | 2.5 TDI | Diesel</span>
                        <span class="price">23000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/112.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">23,000 km | 2004 (11-year-old)</span>
                        <span class="price">23000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/113.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Manual | 6.7|8|4 liters/100km</span>
                        <span class="price">23000€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic1" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic1" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic2" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/121.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Audi | A4 | 1.5 | Petrol</span>
                        <span class="price">21000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/122.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">23,000 km | 2004 (11-year-old)</span>
                        <span class="price">21000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/123.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Manual | 6.7|8|4 liters/100km</span>
                        <span class="price">21000€</span>
                      </div>
                    </div>
                  </div>
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic2" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic2" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic3" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/131.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Alfa Romeo | 33 Stradale | 2.6 | Diesel</span>
                        <span class="price">12000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/132.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">233,000 km | 2001 (14-year-old)</span>
                        <span class="price">12000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/133.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 6.7|8|4 liters/100km</span>
                        <span class="price">12000€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic3" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic3" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic4" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/141.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Alpine | A108/Willys| 2.0 | Petrol</span>
                        <span class="price">3000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/142.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">120,000 km | 2003 (12-year-old)</span>
                        <span class="price">3000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/143.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 6.7|8|4 liters/100km</span>
                        <span class="price">3000€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic4" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic4" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic5" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/151.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Audi | Coupé/Quattro | 3.0 | Diesel</span>
                        <span class="price">6500€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/152.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">5,000 km | 2013 (2-year-old)</span>
                        <span class="price">6500€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/153.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">6500€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic5" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic5" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic6" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/161.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Autobianchi | A112 | 1.6 | Petrol</span>
                        <span class="price">57500€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/162.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">5,000 km | 2013 (2-year-old)</span>
                        <span class="price">57500€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/163.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">57500€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic6" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic6" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic7" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/171.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">BMW | 2000CS | 4.2 | Petrol</span>
                        <span class="price">1300€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/172.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">5,000 km | 2013 (2-year-old)</span>
                        <span class="price">1300€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/173.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">1300€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic7" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic7" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic1" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/121.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Bugatti | Type 50 | 5.6 | Petrol</span>
                        <span class="price">98000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/122.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">5,000 km | 2013 (2-year-old)</span>
                        <span class="price">98000€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/123.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">98000€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic1" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic1" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic8" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/181.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Chevrolet | Caprice | 1.9 | Diesel</span>
                        <span class="price">1200€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/182.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">5,000 km | 2013 (2-year-old)</span>
                        <span class="price">1200€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/183.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">1200€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic8" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic8" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic9" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/191.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Dodge | Aries/Plymouth | 6.0 |Petrol</span>
                        <span class="price">12300€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/192.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">123,000 km | 2013 (5-year-old)</span>
                        <span class="price">12300€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/193.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">12300€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic9" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic9" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic10" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/201.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Ferrari | 250 GT Berlinetta | 2.5 | Petrol</span>
                        <span class="price">400€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/202.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">123,000 km | 2013 (5-year-old)</span>
                        <span class="price">400€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/203.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">400€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic10" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic10" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div id="carousel-example-generic11" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="<?php echo $this->basePath('img/cars/211.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Lagonda | 14/60 | 2.3 | Diesel</span>
                        <span class="price">57500€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/212.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">123,000 km | 2013 (5-year-old)</span>
                        <span class="price">57500€</span>
                      </div>
                    </div>
                    <div class="item">
                      <img src="<?php echo $this->basePath('img/cars/213.jpg') ?>" alt="...">
                      <div class="carousel-caption">
                        <span class="data">Automatic | 4|5|6 l/100km</span>
                        <span class="price">57500€</span>
                      </div>
                    </div>
                  </div>
                
                  <!-- Controls -->
                  <a class="left carousel-control" href="#carousel-example-generic11" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel-example-generic11" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
        </div>
        <div class="footer">
            <p>&copy; 2005 - <?php echo date('Y') ?> by Adseipsum <?php echo $this->translate('All rights reserved.') ?></p>
        </div>
    </div>

    <script>
        $(document).ready(function(){
        	$('#search').on('click', function(){
        		console.log($('#searchForm').serialize());
        	});
        	
        	$('.carousel').carousel({
        		  interval: false
        	});
        	
        	$(".carousel").swiperight(function() {  
    	      $(this).carousel('prev');  
    	    });  
        	
    	   $(".carousel").swipeleft(function() {  
    	      $(this).carousel('next');  
    	   });  
        });
    </script>
    <?php echo $this->inlineScript() ?>
  </body>
</html>
