<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'/>

    <title><?php echo $this->translate('title') ?></title>

    <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open Sans:400,500,600,700,700italic,400italic|Montserrat:300,400,500,700')
                        ->prependStylesheet($this->basePath('css/bootstrap-select.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        //->prependStylesheet('//code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css')
                        ->prependStylesheet($this->basePath('css/fileinput.min.css')) ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath('js/bootstrap-select.js'))
            ->prependFile($this->basePath('js/dropzone.js'))
            ->prependFile($this->basePath('js/jquery.mobile.custom.min.js'))
            //->prependFile('//code.jquery.com/ui/1.11.4/jquery-ui.js')
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/year-select.js'))
            ->prependFile($this->basePath('js/jquery.loadTemplate.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-77751794-1', 'auto');
	  ga('send', 'pageview');

	</script>
      <script>

          var test = [
              {'creationTime' : ''},
              {'creationTime' : '1'},
              {'creationTime' : ''},
              {'creationTime' : ''},
              {'creationTime' : '3'},
              {'creationTime' : '2'},
              {'creationTime' : '5'},
              {'creationTime' : '4'}
          ];

          console.table(test);

          test.sort(function(a,b){

              if(!a.creationTime && b.creationTime){
                  return 1;
              }

              if(a.creationTime && !b.creationTime){
                  return -1;
              }

              if(a.creationTime.length && b.creationTime.length){
                  return (new Date(a.creationTime*1000).getTime() - (new Date(b.creationTime*1000)).getTime());
              }

              return 0;
          });

          console.table(test);
      </script>
  </head>
  <body>

    <div class="container">
        <?php echo $this->content; ?>
    </div>
    <script>

	</script>
    <?php echo $this->inlineScript() ?>
  </body>
</html>
