<div class="row">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
			<div class="navbar-header">
	            <a href="/" id="newAdvertisement" class="btn btn-operational navbar-btn pull-right">All cars</a>
                <a class="navbar-brand navbar-btn" href="/"><img src="/img/logo.png" alt="makina.plus"/></a>
	            <h4><?=$advertisement->make?> <?=$advertisement->model?> <?=$advertisement->year?></h4>
          </div>
		</div>
	</nav>
</div>
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
          	<?php 
	          	$counter = 0;
	          	foreach($advertisement->photos as $photo):
          	?>
	          		<div class="item<?php if($counter == 0){ echo ' active'; }?>">
	          			<img src="/uploads/<?php echo $photo; ?>.jpg">
	          		</div>
          	<?php 
	          	$counter++;
	          	endforeach; 
          	?>
          </div>
          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
	</div>
</div>
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<table class="table" style="margin-top:30px;">
			<tr><td width="120">Make</td><td><?=$advertisement->make?></td></tr>
			<tr><td>Model</td><td><?=$advertisement->model?></td></tr>
			<tr><td>Year</td><td><?=$advertisement->year?></td></tr>
			<tr><td>Transmission</td><td><?=$advertisement->transmission?></td></tr>
			<tr><td>Driver Side</td><td><?=$advertisement->driverSide?></td></tr>
			<tr><td>Wheel Drive</td><td><?=$advertisement->wheelDrive?></td></tr>
			<tr><td>Fuel Type</td><td><?=$advertisement->fuelType?></td></tr>
			<tr><td>Engine Capacity</td><td><?=$advertisement->engineCapacity?>cm<sup>3</sup></td></tr>
			<tr><td>Power</td><td><?=$advertisement->kW?> kW</td></tr>
			<tr><td>Mileage</td><td><?=$advertisement->mileage?></td></tr>
		</table>
		<div id="features">
			<div class="panel list-group">
				<a href="javascript:void(0);" class="list-group-item" data-toggle="collapse" data-target="#sm" data-parent="#features">
					<span>Features</span>
					<span class="glyphicon glyphicon-hand-down pull-right"></span>
				</a>
				<div id="sm" class="sublinks collapse">
					<?php if($advertisement->features) foreach($advertisement->features as $key => $info):?>
						<a class="list-group-item small"><?php echo $info; ?></a>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
		<div>
			<table class="table">
				<tr><td width="120"><span>City:</span></td><td><?=$advertisement->owner['city']?></td></tr>
				<?php if($advertisement->owner['phoneNumber']): ?>
                <tr><td><span>Phone:</span></td><td><a href="tel:<?=$advertisement->owner['phoneNumber']?>"><?=$advertisement->owner['phoneNumber']?></a> <small><i>(click to call)</i></small></td></tr>
                <?php endif;?>
                <tr><td><span>Seller:</span></td><td><?=$advertisement->owner['name']?></td></tr>
                <tr><td><span>Date:</span></td><td><?=$advertisement->date->format('d.m.Y')?></td></tr>
                <tr style="color: white;"><td colspan="2"><?=$advertisement->autodealerId?></td></tr>
			</table>
		</div>
	</div>
</div>
<script>
$(document).ready(function(){
	$('.carousel').carousel({
		interval: false
	});
	
	$(".carousel").swiperight(function() {  
		$(this).carousel('prev');  
	});  
	            	
	$(".carousel").swipeleft(function() {  
		$(this).carousel('next');  
	});
});
</script>