<style>
    .carousel-control.right, .carousel-control.left {
        opacity: 0;
    }
</style>
<div class="row">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="/new" id="newAdvertisement" class="btn btn-operational navbar-btn pull-right"><?php echo $this->translate('Place a Car') ?></a>
<!--             <a href="/new" id="newAdvertisement" class="btn btn-default navbar-btn pull-right">O nas</a> -->
            <a class="navbar-brand navbar-btn" href="/"><img src="/img/logo.png" alt="turbo-cars.com"/></a>
            <h4 id="counter"></h4>
          </div>
        </div><!--/.container-fluid -->
      </nav>
      <div id="navbar" class="navbar-collapse collapse">
      	<form id="searchForm" class="navbar-form" role="search">
            <div id="searchBox">
            		<div class="col-lg-2 col-md-6 col-sm-12 col-xs-12 form-group">
		            	<select id="make" name="make" class="form-control" data-live-search="true">
		                    <option value="0"><?php echo $this->translate('Make') ?></option>
		                    <?php foreach ($make as $maker): ?>
	                        <option value="<?php echo $maker['make']; ?>"><?php echo $maker['make']; ?></option>
	                    	<?php endforeach;?>
	                	</select>
                	</div>
                	<div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 form-group">
		                <select id="model" name="model" class="form-control" data-live-search="true">
		                </select>
	                </div>
	                <div class="col-lg-1 col-md-6 col-sm-12 col-xs-12 form-group">
		                <select id="from" name="from" class="form-control" data-live-search="true">
		                	<option value="1940">1940</option>
		                	<?php for ($i = 1941; $i <= 2016; $i++):?>
	                    	<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
	                    	<?php endfor;?>
	                	</select>
                	</div>
                	<div class="col-lg-1 col-md-6 col-sm-12 col-xs-12 form-group">
	                	<select id="to" name="to" class="form-control" data-live-search="true">
		                	<option value="2016">2016</option>
		                	<?php for ($i = 2015; $i >= 1968; $i--):?>
		                    <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
		                    <?php endfor;?>
		                </select>
	                </div>
	                <div class="col-lg-1 col-md-6 col-sm-12 col-xs-12 form-group">
		                <select id="fuelType" name="fuelType" class="form-control">
		                    <option value="0"><?php echo $this->translate('Fuel') ?></option>
		                    <option value="diesel"><?php echo $this->translate('Diesel') ?></option>
		                    <option value="Benzin"><?php echo $this->translate('Petrol') ?></option>
		                    <option value="gas"><?php echo $this->translate('Gas') ?></option>
		                    <option value="petrolAndGas"><?php echo $this->translate('Petrol + Gas') ?></option>
		                    <option value="hybrid"><?php echo $this->translate('Hybrid') ?></option>
		                    <option value="electric"><?php echo $this->translate('Electric') ?></option>
	                	</select>
                	</div>
            		<div class="col-lg-1 col-md-6 col-sm-12 col-xs-12 form-group">
		                <select id="priceFrom" name="priceFrom" class="form-control" data-live-search="true">
		                </select>
	                </div>
	                <div class="col-lg-1 col-md-6 col-sm-12 col-xs-12 form-group">
		                <select id="priceTo" name="priceTo" class="form-control" data-live-search="true">
		                </select>
	                </div>
                	<div class="col-lg-2 col-md-6 col-sm-12 col-xs-12 form-group">
		                <select id="city" name="city" class="form-control" data-live-search="true">
		                    <option value="0"><?php echo $this->translate('City') ?></option>
		                    <option value="Berlin">Berlin</option>
		                    <option value="Paris">Paris</option>
		                    <option value="London">London</option>
		                    <option value="Rome">Rome</option>
	                	</select>
                	</div>
           	  </div>
		  </form>
      </div><!--/.nav-collapse -->
</div>

<div id="carModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?php echo $this->translate('Loading') ?>...</h4>
      </div>
      <div class="modal-body">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox" data-dismiss="modal">
          </div>
          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon chevron-left" aria-hidden="true"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon chevron-right" aria-hidden="true"></span>
          </a>
        </div>
        &nbsp; &nbsp; &nbsp;
        <div id="carInfo">
            <div id="generalInfo">
            </div>
            <div id="features">
            </div>
            <div id="description">
            </div>
            <div id="ownerInfo">
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <span id="delete" data-id="" style="width:30px; height:30px; float:left; display: block; color: white;"></span>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<div id="dynamic-content" data-skip="0">
			
</div>

        <div class="footer">
            <p>&copy; 2005 - <?php echo date('Y') ?> by Adseipsum <?php echo $this->translate('All rights reserved.') ?></p>
        </div>
        
<script>
$(document).ready(function(){ 
	var container = $('#dynamic-content');
	var processing = false;

	$('#make').on('change', function(){
		enrichModelSelect();
	});

	function enrichModelSelect(){
	    $.ajax({
			  url: "index/getModelByMakeIdJson",
			  data: {'make' : $('#make').val()}
			}).done(function(responce) {
				if(responce.success){
					var model = $("#model").empty();
					model.append($("<option />").val(0).text('Model'));
					$.each(responce.models, function() {
						model.append($("<option />").val(this.model).text(this.model));
					});
					model.selectpicker('refresh');
				}
				container.attr('data-skip', 0).empty();
				if(!processing){ loadPage(container) };
			});
	}

	enrichModelSelect();

	$('body').on('change', '#model, #from, #to, #priceFrom, #priceTo, #fuelType, #city', function(){
	    container.attr('data-skip', 0).empty();
	    if(!processing){ loadPage(container) };
	});
           
    	   $('body').on('click', '.openInfo', function(e){
        	   $.ajax({
        		   url: "index/carInfoJson?id=" + $(this).attr('id'),
       		   }).done(function(responce) {
           		   if(responce.carInfo){
               		   var info = responce.carInfo;
              		   $('#carModal').find('.modal-title').html(info.make + ' ' + info.model);
                	   $('#carModal').find('.carousel-inner').html('');
                	   $('#generalInfo').html('');
                	   $('#features').html('');
                	   $('#description').html('');
                	   $('#ownerInfo').html('');

              		   $.each(info.photos, function( key, value ) {
                  		   
             			   var div = $('#carModal').find('.carousel-inner').append(
                     			   		$('<div>').addClass('item').html(
                             			   		$('<img>')
                     			   				.attr('src', 'uploads/' +  value + '.jpg'))
                     			   				.append($('<span>').addClass('price').html(info.price + '€')));
             			   if(key == 0){
                 			   $(div).find(':first').addClass('active');
             			   }
              		   });

                       $('#carModal').find('.carousel-control.right, .carousel-control.left').css('opacity', 0.5);

                       $('#generalInfo').append($('<table>').addClass('infoTable table')
             		  	  .append('<tr><td width="120"><span>Proizvođač:</span></td><td>' + info.make + '</td></tr>')
             		   	  .append('<tr><td><span>Model:</span></td><td>' + info.model + '</td></tr>')
	             		  .append('<tr><td><span>Year:</span></td><td>' + info.year + '</td></tr>')
	             		  .append('<tr><td><span>Transmission:</span></td><td>' + info.transmission + '</td></tr>')
	             		  .append('<tr><td><span>Driver Side:</span></td><td>' + info.driverSide + '</td></tr>')
	             		  .append('<tr><td><span>Wheel Drive:</span></td><td>' + info.wheelDrive + '</td></tr>')
	             		  .append('<tr><td><span>Fuel Type:</span></td><td>' + info.fuelType + '</td></tr>')
	             		  .append('<tr><td><span>Engine Capacity:</span></td><td>' + info.engineCapacity + ' cm<sup>3</sup></td></tr>')
	             		  .append('<tr><td><span>Power:</span></td><td>' + info.kW + ' kW</tr>')
	             		  .append('<tr><td><span>Mileage:</span></td><td>' + info.mileage + ' km</td></tr>'));

                       $('#features').append(
                        	  $('<div>')
                        	  .addClass('panel list-group')
                        	  .append(
                            	      $('<a>')
                            	      .attr('href', '#')
                            	      .attr('data-toggle', 'collapse')
                            	      .attr('data-target', '#sm')
                            	      .attr('data-parent', '#menu')
                            	      .addClass('list-group-item')
                            	      .append($('<span>').html('Features'))
                                      .append($('<span>').addClass('glyphicon glyphicon-hand-down pull-right'))
                        	      )
                        	  .append(
                                	  $('<div>').attr('id', 'sm').addClass('sublinks collapse')
                               )
                       );
                       $.each(info.features, function( key, value ) {
                           $('#features .sublinks').append($('<a>').addClass('list-group-item small').html(value));
                       });

                	   $('#description').append($('<table>').attr('id', 'description').addClass('table').append('<tr><td colspan="2">' + info.description + '</td></tr>'));

                	   var t = info.date.date.split(/[- :]/);
                  	   var date = new Date(t[0], t[1]-1, t[2], t[3], t[4], t[5]);
                	  
                	   $('#ownerInfo').append(
                        	   $('<table>').attr('id', 'ownerInfoTable').addClass('table')
                        	   .append('<tr><td width="120"><span>City:</span></td><td>' + info.owner[2] + '</td></tr>')
                	   		   .append('<tr><td><span>Phone:</span></td><td><a href="tel:' + info.owner[0] + '">' + info.owner[0] + '</a> <small><i>(click to call)</i></small></td></tr>')
                	           .append('<tr><td><span>Seller:</span></td><td>' + info.owner[1] + '</td></tr>')
                	           .append('<tr><td><span>Date:</span></td><td>' + date.toLocaleDateString() + '</td></tr>')
                	           );

                	   $('#delete').html(info._id);
           		   }
   		       });

               e.preventDefault();
    	   });

    	   $('body').on('click', '#delete', function(e){
			   console.log(1222);
    		   $.ajax({
        		   url: "index/remove-json?id=" + $(this).html(),
       		   }).done(function(responce) {
           		   
       		   });
    	   });

    	   $('body').on('keydown', '#search', function(e){
    		   $.ajax({
        		   url: "index/searchTag?tag=" + $(this).val(),
       		   }).done(function(responce) {
           		   console.log(responce);
       		   });
    	   });

    	   $('body').bind('slide.bs.carousel', '.carousel', function (e) {
   		       if(e.direction == 'left'){
	               var url = $(e.target).find('.item.active').next().find("img").attr('alt'); 
	               $(e.target).find('.item.active').next().find("img").attr("src", url);
   		       }else{
      		       var url = $(e.target).find('.item.active').prev().find("img").attr('alt'); 
        		   if(url != undefined){
 	               	   $(e.target).find('.item.active').prev().find("img").attr("src", url);
        		   }else{
        			   url = $(e.target).find(':last-child').find("img").attr('alt');
        			   $(e.target).find(':last-child').find("img").attr("src", url);
        		   }
   		       }
           });

    	   if(!processing){ loadPage(container) };

    	   
    	   function loadPage(container){

    	       processing = true;
        	   $.ajax({
        		   url: "index/getPage",
        		   data: {
            		   'skip' : container.attr('data-skip'),
            		   'make' : $('#make').val(),
            		   'model' : $('#model').val(),
            		   'from' : $('#from').val(),
				       'to' : $('#to').val(),
				       'priceFrom' : $('#priceFrom').val(),
				       'priceTo' : $('#priceTo').val(),
				       'fuelType' : $('#fuelType').val(),
				       'city' : $('#city').val()
            		   }
       		   }).done(function(responce) {
           		   
       			    if(Object.keys(responce.cars).length == 0){
						return false;
					}
          			var firstFlag = true;
           		    var row = $('<div>').addClass('row');
           		    
          			$.each(responce.cars, function( key, car ) {
          				var colDiv = $('<div>').addClass('col-lg-4 col-md-6 col-sm-6 col-xs-12');
          					
          				var slide = $('<div>').attr('id', car._id).addClass('carousel slide').attr('data-ride', 'carousel');
          				var carouselInner = $('<div>')
						          				.addClass('carousel-inner')
						          				.attr('role', 'listbox')
						          				.attr('id', car._id)
						      					.attr('data-toggle', 'modal')
						      					.attr('data-target', '#carModal')
						      					.addClass('openInfo');

          				//photos
          				$.each(car.photos, function( photo_id, photo ) {
              				
          					var item = $('<div>').addClass('item');
              				var path = 'uploads/' + photo + '.jpg';
          					if(photo_id == 0){
          						item.addClass('active');
          						item.append($('<img>').attr('src', path).attr('draggable', false));
          					}else{
          						item.append($('<img>').attr('alt', path).attr('draggable', false));
          					}
          					
          					carouselInner.append(item);
          				});
          				slide.append(carouselInner);

          				if(firstFlag){
            				//slide.append($('<div>').addClass('favorite').html('<span class="glyphicon glyphicon-star"></span>'));
          				}

						//car info
          				var info = $('<div>').addClass('data');
          				info.append(
                  				$('<div>').addClass('info').html(
            						$('<a>').attr('href', '/advertisement/' + car._id)
            							.html(
                    							//<span style="color: #f63e3e;">&#8226;</span>
                    							car.make + ' ' + 
                    							car.model + ' ' + 
                    							car.year + ' <br/>' + 
                    							addCommas(car.mileage) + '<span style="text-transform: lowercase; margin-left:2px;">km</span> ' +
                    							car.fuelType + '  ' +
                    							car.engineCapacity + ' <span class="cm">cm<sup>3</sup></span> ' +   
                    							car.transmission + ' ' 
                    							
                    							//getFuelTypeSymbol(car.fuelType)
                    						)
                          		)
                        );
          				info.append($('<div>').addClass('price').html(car.price + '€</span>'));
          				slide.append(info);

          				//controls
          				var controls = $('<div>').addClass('controls');
          				var leftControl = $('<a>')
				          				.addClass('left carousel-control')
				          				.attr('href', '#' + car._id)
				          				.attr('role', 'button')
				          				.attr('data-slide', 'prev')
				          				.append($('<span>').addClass('glyphicon chevron-left').attr('aria-hidden', 'true'))
				        controls.append(leftControl);
          				
          				var rightControl = $('<a>')
				          				.addClass('right carousel-control')
				          				.attr('href', '#' + car._id)
				          				.attr('role', 'button')
				          				.attr('data-slide', 'next')
				          				.append($('<span>').addClass('glyphicon chevron-right').attr('aria-hidden', 'true'))
				        controls.append(rightControl);
								        
				        slide.append($('<div>').append(controls));
				        
          				row.append(colDiv.append(slide));
          				
              			//set skip
          				if(firstFlag){ 
                      	   	container.attr('data-skip',  parseInt(container.attr('data-skip')) + Object.keys(responce.cars).length); 
                  	   	}
          				firstFlag = false; 
           		    });
          			container.append(row);

          			$('#counter').html($('<span>').html(responce.count + ' auto listed'));

          			$(".carousel").swiperight(function() {  
          				$(this).carousel('prev');  
          			});  
          			            	
          			$(".carousel").swipeleft(function() {  
          				$(this).carousel('next');  
          			}); 

       		   }).always(function() {
          		    processing = false;
        	   });
        	   
           }

	$(window).scroll(function() {
		if (  document.documentElement.clientHeight + $(document).scrollTop() >= document.body.offsetHeight )
		{ 
		    if(!processing){ loadPage(container) };
		}
	});

	$('.carousel').carousel({
		interval: false
	});
	
	$(".carousel").swiperight(function() {  
		$(this).carousel('prev');  
	});  
	            	
	$(".carousel").swipeleft(function() {  
		$(this).carousel('next');  
	});

	$('#dynamic-content').on('mouseenter', '.carousel', function(){
		$(this).find('.carousel-control.right, .carousel-control.left').css('opacity', 0.5);
	});
	
	$('#dynamic-content').on('mouseleave', '.carousel', function(){
		$(this).find('.carousel-control.right, .carousel-control.left').css('opacity', 0);
	});

	$("#priceTo, #priceFrom").on('change', function(){
	    bindPrice();
	});

	function bindPrice(){
		var priceFrom = $("#priceFrom").val();
		var priceTo = $("#priceTo").val();
	    if(parseInt(priceFrom) > parseInt(priceTo)){
	        $("#priceTo").val(priceFrom);
	    }

	    if(parseInt(priceTo) < parseInt(priceFrom)){
	        $("#priceFrom").val(priceTo);
	    }
	}

	function addCommas(nStr)
	{
		nStr += '';
		x = nStr.split('.');
		x1 = x[0];
		x2 = x.length > 1 ? '.' + x[1] : '';
		var rgx = /(\d+)(\d{3})/;
		while (rgx.test(x1)) {
			x1 = x1.replace(rgx, '$1' + ',' + '$2');
		}
		return x1 + x2;
	}

	function getFuelTypeSymbol(fuelType){
		switch(fuelType){
			case 'petrol':
				return 'P';
				break;
			case 'disel':
				return 'D';
				break;
			case 'gas':
				return 'G';
				break;
			case 'petrolAndGas':
				return 'P&G';
				break;
			case 'hybrid':
				return 'H';
				break;
			case 'electric':
				return 'E';
				break;
			default:
				break;
		}
	}

	generatePriceSelects();
	
	function generatePriceSelects(){
		
	    $("#priceFrom").append($('<option>').attr('value', 0).text('€ From'));
	    for(i = 100; i < 5000; i = i + 500){
	        $("#priceFrom").append($('<option>').attr('value', i).text(i + '€'));
	    }

	    for(i = 5000; i < 10000; i = i + 1000){
	        $("#priceFrom").append($('<option>').attr('value', i).text(i + '€'));
	    }

	    for(i = 10000; i < 100000; i = i + 10000){
	        $("#priceFrom").append($('<option>').attr('value', i).text(i + '€'));
	    }

	    $("#priceTo").append($('<option>').attr('value', 0).text('€ To'));
	    for(i = 100000; i > 10000; i = i - 10000){
	        $("#priceTo").append($('<option>').attr('value', i).text(i + '€'));
	    }

	    for(i = 10000; i > 5000; i = i - 1000){
	        $("#priceTo").append($('<option>').attr('value', i).text(i + '€'));
	    }

	    for(i = 5000; i > 500; i = i - 500){
	        $("#priceTo").append($('<option>').attr('value', i).text(i + '€'));
	    }

	    $('select').selectpicker();
	}
	
});
</script>