<div class="row">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">

        <div class="nav-justified text-center">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="glyphicon glyphicon-chevron-down"></span>
          </button>
        </div>

        <a href="/new" id="newAdvertisement" class="btn btn-operational navbar-btn pull-right"><?php echo $this->translate('newAdvertisement') ?></a>

        <div class="language-group">
          <select id="switchLanguage" class="pull-left">
            <option value="sr_SP">CG</option>
            <option value="en_US">EN</option>
            <option value="ru_RU">RU</option>
          </select>
        </div>
        <!--             <a href="/new" id="newAdvertisement" class="btn btn-default navbar-btn pull-right">O nas</a> -->
        <a class="navbar-brand" href="/"><img src="/img/logo.png" style="height: 30px;" alt="makina.plus"/></a>
<!--          <span id="counter"></span>-->
      </div>
    </div><!--/.container-fluid -->
  </nav>
  <div id="navbar" class="navbar-collapse collapse">
    <form id="searchForm" class="navbar-form" role="search">
      <div id="searchBox">
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="make" name="make" class="form-control" data-live-search="true">
            <option value="0"><?php echo $this->translate('select_make') ?></option>
              <?php foreach ($make as $maker): ?>
                <option value="<?php echo $maker['make']; ?>"><?php echo $maker['make']; ?></option>
              <?php endforeach; ?>
          </select>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="model" name="model" class="form-control" data-live-search="true">
          </select>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="fuelType" name="fuelType" class="form-control">
            <option value="0"><?php echo $this->translate('select_fuel_type') ?></option>
            <option value="diesel"><?php echo $this->translate('diesel') ?></option>
            <option value="Benzin"><?php echo $this->translate('petrol') ?></option>
            <option value="gas"><?php echo $this->translate('gas') ?></option>
            <option value="petrolAndGas"><?php echo $this->translate('petrolAndGas') ?></option>
            <option value="hybrid"><?php echo $this->translate('hybrid') ?></option>
            <option value="electric"><?php echo $this->translate('electric') ?></option>
          </select>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="city" name="city" class="form-control" data-live-search="true">
            <option value="0"><?php echo $this->translate('select_location') ?></option>
              <?php foreach ($cities as $city): ?>
                <option value="<?= $city['name'] ?>"><?= $city['name'] ?></option>
              <?php endforeach; ?>
          </select>
        </div>
        <div class="col-lg-1 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="from" name="from" class="form-control year" data-live-search="true">

          </select>
        </div>
        <div class="col-lg-1 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="to" name="to" class="form-control year" data-live-search="true">

          </select>
        </div>
        <div class="col-lg-1 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="priceFrom" name="priceFrom" class="form-control" data-live-search="true">
          </select>
        </div>
        <div class="col-lg-1 col-md-3 col-sm-6 col-xs-6 form-group">
          <select id="priceTo" name="priceTo" class="form-control" data-live-search="true">
          </select>
        </div>
      </div>
    </form>
  </div><!--/.nav-collapse -->
</div>

<div id="carModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?php echo $this->translate('loading') ?>...</h4>
      </div>
      <div class="modal-body">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox" data-dismiss="modal">
          </div>
          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon chevron-left" aria-hidden="true"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon chevron-right" aria-hidden="true"></span>
          </a>
        </div>
        &nbsp; &nbsp; &nbsp;
        <div id="carInfo">
          <div id="generalInfo">
          </div>
          <div id="features">
          </div>
          <div id="description">
          </div>
          <div id="ownerInfo">
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <span id="delete" data-id="" style="width:30px; height:30px; float:left; display: block; color: white;"></span>
        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('close') ?></button>
      </div>
    </div>

  </div>
</div>

<div id="dynamic-content" data-skip="0">

</div>

<div class="footer">
  <p>&copy; 2005 - <?php echo date('Y') ?> by Adseipsum <?php echo $this->translate('copyright') ?></p>
</div>

<script id="info-template" type="text/html">
    <div data-content="year"></div>
    <div data-content="fuelType"></div>
    <div data-content="transmission"></div>
    <div data-content="engineCapacity"></div>
    <div data-content="city"></div>
    <div class="phoneNumber" data-content="phoneNumber"></div>
    <div class="features" data-content="features"></div>
    <div class="description" data-content="description"></div>
    <div class="date" data-content="date"></div>
</script>

<script>
  $(document).ready(function() {
    var container = $('#dynamic-content');
    var processing = false;
    var $switcher = $('#switchLanguage');

    $('#make').on('change', function() {
      enrichModelSelect();
    });

    $switcher.val('<?= $language ?>');
    $("#switchLanguage option[value='<?= $language ?>']").hide();

    $switcher.on('change', function($e) {
      $e.preventDefault();

      $.ajax({
        type: 'POST',
        url: '/index/language',
        data: {'language': $(this).val()},
      }).done(function(responce) {
        if (responce.success) {
          setTimeout(function() {
            window.location.reload();
          }, 50);
        }
      });
    });

    function enrichModelSelect() {
      $.ajax({
        url: 'index/getModelByMakeIdJson',
        data: {'make': $('#make').val()},
      }).done(function(responce) {
        if (responce.success) {
          var model = $('#model').empty();
          model.append($('<option />').val(0).text('<?php echo $this->translate('select_model') ?>'));
          $.each(responce.models, function() {
            model.append($('<option />').val(this.model).text(this.model));
          });
          model.selectpicker('refresh');
        }
        container.attr('data-skip', 0).empty();
        if (!processing) { loadPage(container); }
        ;
      });
    }

    enrichModelSelect();

    $('body').on('change', '#model, #from, #to, #priceFrom, #priceTo, #fuelType, #city', function() {
      container.attr('data-skip', 0).empty();
      if (!processing) { loadPage(container); }
      ;
    });

    $('body').on('click', '.openInfo', function(e) {
      var info = $(this).find('.info');
      if (info.hasClass('collapsed')) {
        info.removeClass('collapsed').find('div').show();
      }
      else {
        info.addClass('collapsed').find('div').hide();
        $(this).find('.info div:nth-child(-n+6)').show();
      }

      e.preventDefault();
      return;
    });

    $('body').on('click', '#delete', function(e) {
      $.ajax({
        url: 'index/remove-json?id=' + $(this).html(),
      }).done(function(responce) {

      });
    });

    $('body').on('keydown', '#search', function(e) {
      $.ajax({
        url: 'index/searchTag?tag=' + $(this).val(),
      }).done(function(responce) {
        console.log(responce);
      });
    });

    //solve this using preloadPhotos
  $('body').bind('slide.bs.carousel', '.carousel', function(e) {
      if (e.direction == 'left') {
          var url = $(e.target).find('.item.active').next().find('img').attr('alt');
          $(e.target).find('.item.active').next().find('img').attr('src', url);
      }
      else {
          var url = $(e.target).find('.item.active').prev().find('img').attr('alt');
          if (url != undefined) {
              $(e.target).find('.item.active').prev().find('img').attr('src', url);
          }
          else {
              url = $(e.target).find(':last-child').find('img').attr('alt');
              $(e.target).find(':last-child').find('img').attr('src', url);
          }
      }

	  preloadImage(url);
  });

    if (!processing) { loadPage(container); }
    ;

    function preloadPhotos(id) {
      var target = '#' + id;
      var nextURL = $(target).find('.item.active').next().find('img').attr('alt');
      if (nextURL != undefined) {
        $(target).find('.item.active').next().find('img').attr('src', nextURL);
        preloadImage(nextURL);
      }

      var previousURL = $(target).find('.item.active').prev().find('img').attr('alt');
      if (previousURL != undefined) {
        $(target).find('.item.active').prev().find('img').attr('src', previousURL);
        preloadImage(previousURL);
      }
      else {
        previousURL = $(target).find(':last-child').find('img').attr('alt');
        $(target).find(':last-child').find('img').attr('src', previousURL);
        preloadImage(previousURL);
      }
    }

	  function preloadImage(url)
	  {
		  var img = new Image();
		  img.src = url;

		  return img;
	  }

    function loadPage(container) {

      processing = true;
      $.ajax({
        url: 'index/getPage',
        data: {
          'skip': container.attr('data-skip'),
          'make': $('#make').val(),
          'model': $('#model').val(),
          'from': $('#from').val(),
          'to': $('#to').val(),
          'priceFrom': $('#priceFrom').val(),
          'priceTo': $('#priceTo').val(),
          'fuelType': $('#fuelType').val(),
          'city': $('#city').val(),
        },
      }).done(function(responce) {

        if (Object.keys(responce.cars).length == 0) {
          return false;
        }
        var firstFlag = true;
        var row = $('<div>').addClass('row');

        $.each(responce.cars, function(key, car) {
          var colDiv = $('<div>').addClass('col-lg-4 col-md-6 col-sm-6 col-xs-12');

          var slide = $('<div>').attr('id', car._id).addClass('carousel slide').attr('data-ride', 'carousel');
          var carouselInner = $('<div>').addClass('carousel-inner').attr('role', 'listbox').attr('id', car._id)
//						      					.attr('data-toggle', 'modal')
//						      					.attr('data-target', '#carModal')
          ;

          //photos
          $.each(car.photos, function(photo_id, photo) {

            var item = $('<div>').addClass('item');
            var path = 'uploads/' + photo + '.jpg';
            if (photo_id == 0) {
              item.addClass('active');
              item.append($('<img>').attr('src', path).attr('draggable', false));
            }
            else {
              item.append($('<img>').attr('alt', path).attr('draggable', false));
            }

            carouselInner.append(item);
          });
          slide.append(carouselInner);

          if (firstFlag) {
            //slide.append($('<div>').addClass('favorite').html('<span class="glyphicon glyphicon-star"></span>'));
          }

          //car info
          var data = $('<div>').addClass('data').addClass('openInfo');
          slide.append(
          	$('<div>').addClass('car-title')
                .append($('<a>').attr('href', '/advertisement/' + car._id).text(car.make + ' ' + car.model))
                .append($('<span>').addClass('price').html('€ ' + car.price + '</span>')));

          var info = $('<div>').addClass('info');

          var t = car.date.date.split(/[- :]/);
          var date = new Date(t[0], t[1] - 1, t[2], t[3], t[4], t[5]);

        var features = $('<span>');
        var features_length = car.features.length;
        $.each(car.features, function(key, value) {
            features.append(value);
	        if (key != (features_length - 1)) {
		        features.append(', ');
	        }
        });

          info.loadTemplate($('#info-template'),
              {
                engineCapacity: car.engineCapacity + ' <span class="cm">cm<sup>3</sup></span>',
                year: car.year,
                fuelType: car.fuelType,
                transmission: car.transmission,
                mileage: addCommas(car.mileage) + '<span style="text-transform: lowercase; margin-left:2px;">km</span>',
                city: car.owner['city'],
                phoneNumber: '<a href="tel:' + car.owner['phoneNumber'] + '">' + car.owner['phoneNumber'] + '</a></td></tr>',
                date: date.toLocaleDateString(),
                features: features,
                description: car.description
              }
          );

          info.addClass('collapsed').find('div').hide();
          info.find('div:nth-child(-n+6)').show();

          data.append(info);
          slide.append(data);

          //Hide useless carousel arrows
          if ($(carouselInner).children('div').length > 1) {
            //controls
            var controls = $('<div>').addClass('controls');
            var leftControl = $('<a>').addClass('left carousel-control').attr('href', '#' + car._id).attr('role', 'button').attr('data-slide', 'prev').append($('<span>').addClass('glyphicon chevron-left').attr('aria-hidden', 'true'));
            controls.append(leftControl);

            var rightControl = $('<a>').addClass('right carousel-control').attr('href', '#' + car._id).attr('role', 'button').attr('data-slide', 'next').append($('<span>').addClass('glyphicon chevron-right').attr('aria-hidden', 'true'));
            controls.append(rightControl);

	          carouselInner.parent().append(controls);
          }

          row.append(colDiv.append(slide));

          //set skip
          if (firstFlag) {
            container.attr('data-skip', parseInt(container.attr('data-skip')) + Object.keys(responce.cars).length);
          }
          firstFlag = false;
        });
        container.append(row);

        $.each(responce.cars, function(key, car) {
          preloadPhotos(car._id);
        });

        $('#counter').html($('<span>').html(responce.count + ' <?= $this->translate("auto_listed") ?>'));

        $('.carousel').swiperight(function() {
          $(this).carousel('prev');
        });

        $('.carousel').swipeleft(function() {
          $(this).carousel('next');
        });

      }).always(function() {
        processing = false;
      });

    }

    $(window).scroll(function() {
      if (document.documentElement.clientHeight + $(document).scrollTop() >= document.body.offsetHeight - 100) {
        if (!processing) {
        	loadPage(container);
        }
      }
    });

    $('.carousel').carousel({
      interval: false,
    });

    $('.carousel').swiperight(function() {
      $(this).carousel('prev');
    });

    $('.carousel').swipeleft(function() {
      $(this).carousel('next');
    });

    $('#dynamic-content').on('mouseenter', '.carousel', function() {
      $(this).find('.carousel-control.right, .carousel-control.left').css('opacity', 0.5);
    });

    $('#dynamic-content').on('mouseleave', '.carousel', function() {
      $(this).find('.carousel-control.right, .carousel-control.left').css('opacity', 0);
    });

    $('#priceTo, #priceFrom').on('change', function() {
      bindPrice();
    });

    $('#navbar').on('show.bs.collapse', function() {
      $('.navbar-toggle').find('.glyphicon').removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-up');
    });

    $('#navbar').on('hide.bs.collapse', function(){
      $('.navbar-toggle').find('.glyphicon').removeClass('glyphicon-chevron-up').addClass('glyphicon-chevron-down');
    });

    $('#from').yearselect({
      start: 1950,
      end: 2017,
      order: 'asc'
    });

    $('#to').yearselect({
      start: 1950,
      end: 2017,
      order: 'desc'
    });

    function bindPrice() {
      var priceFrom = $('#priceFrom').val();
      var priceTo = $('#priceTo').val();
      if (parseInt(priceFrom) > parseInt(priceTo)) {
        $('#priceTo').val(priceFrom);
      }

      if (parseInt(priceTo) < parseInt(priceFrom)) {
        $('#priceFrom').val(priceTo);
      }
    }

    function addCommas(nStr) {
      nStr += '';
      x = nStr.split('.');
      x1 = x[0];
      x2 = x.length > 1 ? '.' + x[1] : '';
      var rgx = /(\d+)(\d{3})/;
      while (rgx.test(x1)) {
        x1 = x1.replace(rgx, '$1' + ',' + '$2');
      }
      return x1 + x2;
    }

    function getFuelTypeSymbol(fuelType) {
      switch (fuelType) {
        case 'petrol':
          return 'P';
          break;
        case 'disel':
          return 'D';
          break;
        case 'gas':
          return 'G';
          break;
        case 'petrolAndGas':
          return 'P&G';
          break;
        case 'hybrid':
          return 'H';
          break;
        case 'electric':
          return 'E';
          break;
        default:
          break;
      }
    }

    generatePriceSelects();

    function generatePriceSelects() {

      $('#priceFrom').append($('<option>').attr('value', 0).text('€ <?= $this->translate("price_from") ?>'));
      for (i = 100; i < 5000; i = i + 500) {
        $('#priceFrom').append($('<option>').attr('value', i).text(i + '€'));
      }

      for (i = 5000; i < 10000; i = i + 1000) {
        $('#priceFrom').append($('<option>').attr('value', i).text(i + '€'));
      }

      for (i = 10000; i < 100000; i = i + 10000) {
        $('#priceFrom').append($('<option>').attr('value', i).text(i + '€'));
      }

      $('#priceTo').append($('<option>').attr('value', 0).text('€ <?= $this->translate("price_to") ?>'));
      for (i = 100000; i > 10000; i = i - 10000) {
        $('#priceTo').append($('<option>').attr('value', i).text(i + '€'));
      }

      for (i = 10000; i > 5000; i = i - 1000) {
        $('#priceTo').append($('<option>').attr('value', i).text(i + '€'));
      }

      for (i = 5000; i > 500; i = i - 500) {
        $('#priceTo').append($('<option>').attr('value', i).text(i + '€'));
      }

      $('select').selectpicker();
    }

  });
</script>