<div class="row">
	<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a href="/" id="newAdvertisement" class="btn btn-operational navbar-btn pull-right"><?php echo $this->translate('List all cars') ?></a>
<!--             <a class="navbar-brand navbar-btn" href="/"><img src="/img/logo.png" alt="vozila.me"/></a> -->
            <h4><?php echo $this->translate('New car') ?></h4>
          </div>
        </div><!--/.container-fluid -->
      </nav>
</div>
<div class="row">
    <div id="advertisementBlock" class="col-lg-12">
        <form id="advertisementForm" action="/new" method="post" role="form" class="form" enctype="multipart/form-data">
        	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group"><h3 class="text-center"><?php echo $this->translate('Main information') ?></h3></div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="brand" class="control-label"><?php echo $this->translate('Make') ?>:</label>
                <select id="make" name="make" class="form-control" data-error="Please select mark" required>
                    <option value="" selected disabled><?php echo $this->translate('Choose make') ?></option>
                    <?php foreach ($make as $maker): ?>
                        <option value="<?php echo $maker['make']; ?>"><?php echo $maker['make']; ?></option>
                    <?php endforeach;?>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="model" class="control-label"><?php echo $this->translate('Model') ?>:</label>
                <select id="model" name="model" class="form-control" data-error="Please select model" required>
                    <option value="" selected disabled><?php echo $this->translate('First choose make') ?></option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="modification" class="control-label"><?php echo $this->translate('Modification') ?>:</label>
                <input type="text" name="modification" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="year" class="control-label"><?php echo $this->translate('Manufacture year') ?>:</label>
                <input type="number" name="year" id="year" class="form-control" data-minlength="4" data-error="<?php echo $this->translate('Please add car manufacture year') ?>" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="transmission"><?php echo $this->translate('Transmission') ?>:</label>
                <select id="transmission" name="transmission" class="form-control" data-error="<?php echo $this->translate('Please select transmission type') ?>" required>
                    <option value=""><?php echo $this->translate('Choose transmission type') ?></option>
                    <option value="manual"><?php echo $this->translate('Manual') ?></option>
                    <option value="automatic"><?php echo $this->translate('Automatic') ?></option>
                    <option value="tiptronik"><?php echo $this->translate('Tiptronic') ?></option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="driverSide" class="control-label"><?php echo $this->translate('Driver side') ?>:</label>
                <select id="driverSide" name="driverSide" class="form-control" data-error="<?php echo $this->translate('Please select driver side') ?>" required>
                    <option value=""><?php echo $this->translate('Choose driver side') ?></option>
                    <option value="left"><?php echo $this->translate('Left') ?></option>
                    <option value="right"><?php echo $this->translate('Right') ?></option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="wheelDrive" class="control-label"><?php echo $this->translate('Wheel drive') ?>:</label>
                <select id="wheelDrive" name="wheelDrive" class="form-control" data-error="<?php echo $this->translate('Please select wheel drive') ?>" required>
                    <option value=""><?php echo $this->translate('Choose wheel drive') ?></option>
                    <option value="front"><?php echo $this->translate('Front-wheel drive') ?></option>
                    <option value="rear"><?php echo $this->translate('Rear-wheel drive') ?></option>
                    <option value="all"><?php echo $this->translate('Full-wheel drive') ?></option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="fuelType" class="control-label"><?php echo $this->translate('Fuel type') ?>:</label>
                <select id="fuelType" name="fuelType" class="form-control" data-error="<?php echo $this->translate('Please select fuel type') ?>" required>
                    <option value=""><?php echo $this->translate('Choose fuel type') ?></option>
                    <option value="diesel"><?php echo $this->translate('Disel') ?></option>
                    <option value="petrol"><?php echo $this->translate('Petrol') ?></option>
                    <option value="gas"><?php echo $this->translate('Gas') ?></option>
                    <option value="petrolAndGas"><?php echo $this->translate('Petrol + Gas') ?></option>
                    <option value="hybrid"><?php echo $this->translate('Hybrid') ?></option>
                    <option value="electric"><?php echo $this->translate('Electric') ?></option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
<!--             <div class="form-group"> -->
<!--                 <label for="engineType">Motor:</label> -->
<!--                 <input type="text" name="engineType" class="form-control"/> -->
<!--             </div> -->
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="engineCapacity" class="control-label"><?php echo $this->translate('Engine capacity') ?>: (cm3)</label>
                <input type="text" name="engineCapacity" class="form-control" data-minlength="3" data-error="<?php echo $this->translate('Please add engine capacity in cm3') ?>" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="enginePower" class="control-label"><?php echo $this->translate('Power') ?>: (kW)</label>
                <input type="text" name="enginePower" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="color" class="control-label"><?php echo $this->translate('Color') ?>:</label>
                <input type="text" name="color" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="mileage" class="control-label"><?php echo $this->translate('Mileage') ?>: (km)</label>
                <input type="text" name="mileage" class="form-control" data-error="<?php echo $this->translate('Please add mileage') ?>" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group"><h3 class="text-center"><?php echo $this->translate('Features') ?></h3></div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 form-group">
            	<ul class="list-group">
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="airConditioning" name="features[airConditioning]"><?php echo $this->translate('Air conditioning') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="abs" name="features[abs]"><?php echo $this->translate('ABS') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="esp" name="features[esp]"><?php echo $this->translate('ESP') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="audio" name="features[audio]"><?php echo $this->translate('Audio system') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="powerAssistedSteering" name="features[powerAssistedSteering]"><?php echo $this->translate('Power Assisted Steering') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="sunRoof" name="features[sunRoof]"><?php echo $this->translate('Sun roof') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="towHook" name="features[towHook]"><?php echo $this->translate('Tow hook') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="climatisation" name="features[climatisation]"><?php echo $this->translate('Climatisation') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="electricWindows" name="features[electricWindows]"><?php echo $this->translate('Electric Windows') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="electricHeatedSeats" name="features[electricHeatedSeats]"><?php echo $this->translate('Electric Heated Seats') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="centralLocking" name="features[centralLocking]"><?php echo $this->translate('Central Locking') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="metallicColor" name="features[metallicColor]"><?php echo $this->translate('Metallic Color') ?></label></li>
                </ul>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 form-group">
	            <ul class="list-group">
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="parkingSensors" name="features[parkingSensors]"><?php echo $this->translate('Parking Sensors') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="fogLamp" name="features[fogLamp]"><?php echo $this->translate('Fog Lamp') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="leather" name="features[leatherSeats]"><?php echo $this->translate('Leather Seats') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="airbags" name="features[airbags]"><?php echo $this->translate('Airbags') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="alarm" name="features[alarm]"><?php echo $this->translate('Alarm') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="remoteLock" name="features[remoteLock]"><?php echo $this->translate('Remote Lock') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="alloyWheels" name="features[alloyWheels]"><?php echo $this->translate('Alloy Wheels') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="immobilizer" name="features[immobilizer]"><?php echo $this->translate('Immobilizer') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="navigationSystem" name="features[navigationSystem]"><?php echo $this->translate('Navigation System') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="cruiseControl" name="features[cruiseControl]"><?php echo $this->translate('Cruise Control') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="panoramicRoof" name="features[panoramicRoof]"><?php echo $this->translate('Panoramic Roof') ?></label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="xenonHeadlights" name="features[xenonHeadlights]"><?php echo $this->translate('Xenon Headlights') ?></label></li>
	            </ul>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
                <label for="description" class="control-label"><?php echo $this->translate('Description') ?>:</label>
                <textarea name="description" class="form-control"></textarea>
                <div class="help-block with-errors"></div>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group"><h3 class="text-center"><?php echo $this->translate('Owner information') ?></h3></div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="price" class="control-label"><?php echo $this->translate('Price') ?>:</label>
                <div class="input-group">
                  <span class="input-group-addon">€</span>
                  <input type="text" name="price" id="price" class="form-control" data-error="<?php echo $this->translate('Please put your price') ?>" required/>
                </div>
                <div class="help-block with-errors"></div>
            </div>
            
            <div class=" col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="phoneNumber" class="control-label"><?php echo $this->translate('Phone number') ?>:</label>
                <input type="text" name="owner[phoneNumber]" class="form-control" data-error="<?php echo $this->translate('Please add telefon number') ?>" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="email" class="control-label"><?php echo $this->translate('Email') ?>:</label>
                <div class="input-group">
	                <span class="input-group-addon">@</span>
	                <input type="email" name="owner[email]" class="form-control" data-error="<?php echo $this->translate('Email address is invalid') ?>" />
	            </div>
	            <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="city" class="control-label"><?php echo $this->translate('City') ?>:</label>
                <select id="city" name="owner[city]" class="form-control" data-error="<?php echo $this->translate('Please choose city where car located') ?>" required>
                    <option value="" disabled><?php echo $this->translate('Choose city') ?></option>
                    <option value="Berlin">Berlin</option>
                    <option value="Paris">Paris</option>
                    <option value="London">London</option>
                    <option value="Rome">Rome</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="name" class="control-label"><?php echo $this->translate('Name') ?>:</label>
                <input type="text" name="owner[name]" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
				<div class="table table-striped files" id="previews">
					<div id="template" class="file-row col-lg-4 col-md-4 col-sm-6 col-xs-12">
						<!-- This is used as the file preview template -->
						<div>
							<span class="preview"><img data-dz-thumbnail /><div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
									<div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
							</div></span>
						</div>
						<div>
<!-- 							<p class="size" data-dz-size></p> -->
						</div>
						<div class="fileInfo">
							<div class="name word-break" data-dz-name></div>
							<div class="pull-right">
								<button data-dz-remove class="btn btn-operational delete">
									<i class="glyphicon glyphicon-trash"></i>
									<span>Delete</span>
								</button>
							</div>
						</div>
						<div>
							<strong class="error text-danger" data-dz-errormessage></strong>
						</div>
					</div>
				</div>
				
				<div id="actions" class="row">
			      <div class="col-lg-12">
			        <!-- The fileinput-button span is used to style the file input field as button -->
			        <span class="btn btn-lg btn-operational fileinput-button pull-right">
			            <i class="glyphicon glyphicon-plus"></i>
			            <span>Add files</span>
			        </span>
			      </div>
			
			      <div class="col-lg-12">
			        <!-- The global file processing state -->
			        <span class="fileupload-process">
	 				  <div id="total-progress" class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" style="display: none;">
				            <div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
			          </div>
			        </span>
			      </div>
			
			    </div>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group pull-right">
                <button type="submit" id="post" class="btn btn-operational pull-right"><?php echo $this->translate('Post car') ?></button>
                <div class="help-block with-errors"></div>
            </div>
            <input type="hidden" id="carDirectory" name="carDirectory" value=""/>
            <div id="filesInputsContainer"></div>
        </form>
    </div>
</div>

<script>
var carDirectory = '<?= $carDirectory ?>';

$(document).ready(function(){
    $('#carDirectory').val(carDirectory);
    
    // Get the template HTML and remove it from the doument
    var previewNode = document.querySelector("#template");
    previewNode.id = "";
    var previewTemplate = previewNode.parentNode.innerHTML;
    previewNode.parentNode.removeChild(previewNode);

    var myDropzone = new Dropzone(document.body, { // Make the whole body a dropzone
      url: "/index/saveFile", // Set the url
      params: { 
          carDirectory : $('#carDirectory').val()
          },
      maxFilesize: '2000',
      maxFiles: 15,
      thumbnailWidth: 350,
      thumbnailHeight: 220,
      parallelUploads: 15,
      previewTemplate: previewTemplate,
      acceptedFiles: 'image/jpeg, image/png, image/gif',
      autoQueue: true, // Make sure the files aren't queued until manually added
      previewsContainer: "#previews", // Define the container to display the previews
      clickable: ".fileinput-button", // Define the element that should be used as click trigger to select files.
      success: function(file, response){
          if(response){
              $('#carDirectory').val(response.carDirectory);
              $('#filesInputsContainer').append($('<input>').attr('type', 'hidden').attr('name', 'photos[]').attr('value', response.fileId));
          }
      }
    });

    myDropzone.on("addedfile", function(file) {
      $('#post').attr('disabled', true);
      // Hookup the start button
      //file.previewElement.querySelector(".start").onclick = function() { myDropzone.enqueueFile(file); };
    });

    // Update the total progress bar
    myDropzone.on("totaluploadprogress", function(progress) {
    	document.querySelector("#total-progress .progress-bar").style.width = progress + "%";
    });

    myDropzone.on("sending", function(file) {
      // Show the total progress bar when upload starts
      document.querySelector("#total-progress").style.display = "block";
      // And disable the start button
      //file.previewElement.querySelector(".start").setAttribute("disabled", "disabled");
    });

    // Hide the total progress bar when nothing's uploading anymore
    myDropzone.on("queuecomplete", function(progress) {
        $('#post').attr('disabled', false);
    	document.querySelector("#total-progress").style.display = "none";
    });

    // Setup the buttons for all transfers
    // The "add files" button doesn't need to be setup because the config
    // `clickable` has already been specified.
//     document.querySelector("#actions .start").onclick = function() {
//       myDropzone.enqueueFiles(myDropzone.getFilesWithStatus(Dropzone.ADDED));
//     };
//     document.querySelector("#actions .cancel").onclick = function() {
//       myDropzone.removeAllFiles(true);
//     };
    
	$('#make').change(function(){
		$.ajax({
		  url: "index/getModelByMakeIdJson",
		  data: {'make' : $(this).val()}
		}).done(function(responce) {
			if(responce.success){
				var model = $("#model").empty();
				$.each(responce.models, function() {
					model.append($("<option />").val(this.model).text(this.model));
				});
			}
		});
	});

	$('#advertisementForm').find('button[type=submit]').on('click', function(e) {
        if ($('#advertisementForm').validator('validate').has('.has-error').length) {
        } else {
            $('#advertisementForm').submit();
        }
        return false;
    });
	
});
</script>

<?php 
	$this->headScript()->prependFile($this->basePath('js/validator.js'));
?>
