<style>
#advertisementBlock{
    color: gray;
    top: 10px;
}

#advertisementBlock .form-group{
    padding: 8px 10px;
}

#advertisementBlock .list-group{
    margin: 8px 3px;
}

.list-group .list-group-item{
    padding: 2px 10px;
}

.help-block{
    display: none;
}

#post{
    background-color: #f63e3e !important;
    color: white;
    font-size: 1.1em;
    font-family: Montserrat,Arial,Helvetica,"Lucida Grande","Lucida Sans",Tahoma,Verdana,sans-serif;
}

h3{
    margin-top: 10px;
    margin-bottom: 5px;
}
</style>

<div class="row">
	<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a href="/" id="newAdvertisement" class="btn btn-operational navbar-btn pull-right">Naslovna</a>
            <a class="navbar-brand navbar-btn" href="/"><img src="/img/logo.png" alt="vozila.me"/></a>
            <h4>Dodaj oglas</h4>
          </div>
        </div><!--/.container-fluid -->
      </nav>
</div>
<div class="row">
    <div id="advertisementBlock" class="col-lg-12">
        <form action="" method="post" role="form" class="form" enctype="multipart/form-data" data-toggle="validator">
        	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group"><h3 class="text-center">Glavno</h3></div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="brand" class="control-label">Marka:</label>
                <select id="make" name="make" class="form-control" data-error="Please select mark" required>
                    <option value="" selected disabled>Izaberite Marku</option>
                    <?php foreach ($make as $maker): ?>
                        <option value="<?php echo $maker['make']; ?>"><?php echo $maker['make']; ?></option>
                    <?php endforeach;?>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="model" class="control-label">Model:</label>
                <select id="model" name="model" class="form-control" data-error="Please select model" required>
                    <option value="" selected disabled>Prvo izaberite marku</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="modification" class="control-label">Modification:</label>
                <input type="text" name="modification" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="year" class="control-label">Godište:</label>
                <input type="number" name="year" id="year" class="form-control" data-minlength="4" data-error="Please add car manufacture year" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="transmission">Mjenjač:</label>
                <select id="transmission" name="transmission" class="form-control" data-error="Please select transmission type" required>
                    <option value="">Izaberite Mjenjač</option>
                    <option value="manual">Manuelni</option>
                    <option value="automatic">Automatski</option>
                    <option value="tiptronik">Tiptronik</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="driverSide" class="control-label">Strana volana:</label>
                <select id="driverSide" name="driverSide" class="form-control" data-error="Please select driver side" required>
                    <option value="">Izaberite Stranu Volana</option>
                    <option value="left">Lijeva</option>
                    <option value="right">Desna</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="wheelDrive" class="control-label">Pogon:</label>
                <select id="wheelDrive" name="wheelDrive" class="form-control" data-error="Please select wheel drive" required>
                    <option value="">Izaberite Pogon</option>
                    <option value="front">Prednja vuča</option>
                    <option value="rear">Zadnja vuča</option>
                    <option value="all">4x4</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="fuelType" class="control-label">Gorivo:</label>
                <select id="fuelType" name="fuelType" class="form-control" data-error="Please select fuel type" required>
                    <option value="">Izaberite Vrstu Goriva</option>
                    <option value="diesel">Dizel</option>
                    <option value="petrol">Benzin</option>
                    <option value="gas">Metan</option>
                    <option value="petrol_and_gas">Benzin + plin</option>
                    <option value="hybrid">Hibridni pogon</option>
                    <option value="electric">Električni pogon</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
<!--             <div class="form-group"> -->
<!--                 <label for="engineType">Motor:</label> -->
<!--                 <input type="text" name="engineType" class="form-control"/> -->
<!--             </div> -->
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="engineCapacity" class="control-label">Kubikaža: (cm3)</label>
                <input type="text" name="engineCapacity" class="form-control" data-minlength="3" data-error="Please add engine capacity in cm3" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="enginePower" class="control-label">Snaga: (kW)</label>
                <input type="text" name="enginePower" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="color" class="control-label">Boja:</label>
                <input type="text" name="color" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="mileage" class="control-label">Kilometraža: (km)</label>
                <input type="text" name="mileage" class="form-control" data-error="Please add mileage" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group"><h3 class="text-center">Komponente</h3></div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 form-group">
            	<ul class="list-group">
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="AC klima" name="features[aac]">AC klima</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="ABS" name="features[abs]">ABS</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="ESP" name="features[esp]">ESP</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Muzika" name="features[audio]">Muzika</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Servo" name="features[powerAssistedSteering]">Servo</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Šiber" name="features[sunroof]">Šiber</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Kuka" name="features[towHook]">Kuka</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Digitalna klima" name="features[climatisation]">Digitalna klima</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Electro podizači" name="features[electricWindows]">Electro podizači</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Grijači sedišta" name="features[electricHeatedSeats]">Grijači sedišta</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Centralna brava" name="features[centralLocking]">Centralna brava</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Metalik boja" name="features[metallicColor]">Metalik boja</label></li>
                </ul>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 form-group">
	            <ul class="list-group">
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Parking senzor" name="features[parkingSensors]">Parking senzor</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Svijetla za maglu" name="features[fogLamp]">Svijetla za maglu</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Koža" name="features[leather]">Koža</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Air bag" name="features[airbags]">Air bag</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Alarm" name="features[alarm]">Alarm</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Alu felne" name="features[alloyWheels]">Alu felne</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Kod ključ" name="features[immobilizer]">Kod ključ</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Navigacija" name="features[navigationSystem]">Navigacija</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Tempomat" name="features[cruiseControl]">Tempomat</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Daljinsko zaključavanje" name="features[remoteLock]">Daljinsko zaključavanje</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Panorama krov" name="features[panoramicRoof]">Panorama krov</label></li>
	                <li class="list-group-item"><label class="checkbox"><input type="checkbox" value="Xenon" name="features[xenonHeadlights]">Xenon</label></li>
	            </ul>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
                <label for="description" class="control-label">Opis:</label>
                <textarea name="description" class="form-control"></textarea>
                <div class="help-block with-errors"></div>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group"><h3 class="text-center">Informacia</h3></div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="price" class="control-label">Cijena:</label>
                <div class="input-group">
                  <span class="input-group-addon">€</span>
                  <input type="text" name="price" id="price" class="form-control" data-error="Please put your price" required/>
                </div>
                <div class="help-block with-errors"></div>
            </div>
            
            <div class=" col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="phoneNumber" class="control-label">Telefon:</label>
                <input type="text" name="owner[phoneNumber]" class="form-control" data-error="Please add telefon number" required/>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="email" class="control-label">Email:</label>
                <div class="input-group">
	                <span class="input-group-addon">@</span>
	                <input type="email" name="owner[email]" class="form-control" data-error="Email address is invalid" />
	            </div>
	            <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="city" class="control-label">Grad:</label>
                <select id="city" name="owner[city]" class="form-control" data-error="Please choose city where car located" required>
                    <option value="" disabled>Izaberite Grad</option>
                    <option value="Podgorica">Podgorica</option>
                    <option value="Nikšić">Nikšić</option>
                    <option value="Pljevlja">Pljevlja</option>
                    <option value="Bijelo Polje">Bijelo Polje</option>
                    <option value="Cetinje">Cetinje</option>
                    <option value="Bar">Bar</option>
                    <option value="Herceg Novi">Herceg Novi</option>
                    <option value="Berane">Berane</option>
                    <option value="Budva">Budva</option>
                    <option value="Ulcinj">Ulcinj</option>
                    <option value="Rožaje">Rožaje</option>
                    <option value="Tivat">Tivat</option>
                    <option value="Dobrota">Dobrota</option>
                    <option value="Kotor">Kotor</option>
                    <option value="Danilovgrad">Danilovgrad</option>
                    <option value="Mojkovac">Mojkovac</option>
                    <option value="Škaljari">Škaljari</option>
                    <option value="Tuzi">Tuzi</option>
                    <option value="Igalo">Igalo</option>
                    <option value="Bijela">Bijela</option>
                    <option value="Plav">Plav</option>
                    <option value="Burtaiši">Burtaiši</option>
                    <option value="Kolašin">Kolašin</option>
                    <option value="Ibarac">Ibarac</option>
                    <option value="Golubovci">Golubovci</option>
                    <option value="Resnik">Resnik</option>
                    <option value="Nedakusi">Nedakusi</option>
                    <option value="Šušanj">Šušanj</option>
                    <option value="Risan">Risan</option>
                    <option value="Ozrinići">Ozrinići</option>
                    <option value="Žabljak">Žabljak</option>
                    <option value="Pokrajci">Pokrajci</option>
                    <option value="Stari Bar">Stari Bar</option>
                    <option value="Donje Luge">Donje Luge</option>
                    <option value="Mojanovići">Mojanovići</option>
                    <option value="Sutomore">Sutomore</option>
                    <option value="Zelenika">Zelenika</option>
                    <option value="Pešca">Pešca</option>
                    <option value="Gusinje">Gusinje</option>
                    <option value="Budimlja">Budimlja</option>
                    <option value="Spuž">Spuž</option>
                    <option value="Polje">Polje</option>
                    <option value="Rastovica">Rastovica</option>
                    <option value="Polja">Polja</option>
                    <option value="Mrčevac">Mrčevac</option>
                    <option value="Plužine">Plužine</option>
                    <option value="Petrovac">Petrovac</option>
                    <option value="Beran Selo">Beran Selo</option>
                    <option value="Bjeliši">Bjeliši</option>
                    <option value="Čeluga">Čeluga</option>
                    <option value="Mataguži">Mataguži</option>
                    <option value="Dolac">Dolac</option>
                    <option value="Đenovići">Đenovići</option>
                    <option value="Lješnica">Lješnica</option>
                    <option value="Prčanj">Prčanj</option>
                    <option value="Mahala">Mahala</option>
                    <option value="Goričani">Goričani</option>
                    <option value="Podi">Podi</option>
                    <option value="Meljine">Meljine</option>
                    <option value="Tomba">Tomba</option>
                    <option value="Andrijevica">Andrijevica</option>
                    <option value="Kumbor">Kumbor</option>
                    <option value="Buče">Buče</option>
                    <option value="Smajlagića Polje">Smajlagića Polje</option>
                    <option value="Kodre">Kodre</option>
                    <option value="Bečići">Bečići</option>
                    <option value="Donja Lastva">Donja Lastva</option>
                    <option value="Židovići">Židovići</option>
                    <option value="Šavnik">Šavnik</option>
                    <option value="Sveti Stefan">Sveti Stefan</option>
                    <option value="Slatina">Slatina</option>
                    <option value="Gradac">Gradac</option>
                    <option value="Perast">Perast</option>
                    <option value="Virpazar">Virpazar</option>
                    <option value="Goransko">Goransko</option>
                    <option value="Bare">Bare</option>
                    <option value="Njegovuđa">Njegovuđa</option>
                    <option value="Rijeka Crnojevića">Rijeka Crnojevića</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 form-group">
                <label for="name" class="control-label">Ime:</label>
                <input type="text" name="owner[name]" class="form-control"/>
                <div class="help-block with-errors"></div>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
                <input id="photos" name="photos[]" type="file" class="file" data-preview-file-type="image" multiple="true" placeholder="Dodaj sliki" data-error="Please add at least two photos" required>
                <div class="help-block with-errors"></div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
                <input type="submit" id="post" class="btn-operational form-control" value="Dodaj"/>
            </div>
        </form>
    </div>
</div>

<?php 
	echo $this->headScript()->prependFile($this->basePath('js/validator.js'));
?>

<script>
$(document).ready(function(){
	$('#photos').fileinput({
	    resizeImage: true,
	    maxImageWidth: 200,
	    maxImageHeight: 200,
	    resizePreference: 'width',
	    maxFileCount: 10
	});

	$('#make').change(function(){
		$.ajax({
		  url: "index/getModelByMakeIdJson",
		  data: {'make' : $(this).val()}
		}).done(function(responce) {
			if(responce.success){
				var model = $("#model").empty();
				$.each(responce.models, function() {
					model.append($("<option />").val(this.model).text(this.model));
				});
			}
		});
	});
	
});
</script>