<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class OldtimersEntityCarHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['_id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['_id']['type'];
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['_id']->setValue($document, $return);
            $hydratedData['_id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['uniqueId']) || (! empty($this->class->fieldMappings['uniqueId']['nullable']) && array_key_exists('uniqueId', $data))) {
            $value = $data['uniqueId'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['uniqueId']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['uniqueId']->setValue($document, $return);
            $hydratedData['uniqueId'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['date'])) {
            $value = $data['date'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['date']->setValue($document, clone $return);
            $hydratedData['date'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['popularity']) || (! empty($this->class->fieldMappings['popularity']['nullable']) && array_key_exists('popularity', $data))) {
            $value = $data['popularity'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['popularity']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['popularity']->setValue($document, $return);
            $hydratedData['popularity'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['garageId']) || (! empty($this->class->fieldMappings['garageId']['nullable']) && array_key_exists('garageId', $data))) {
            $value = $data['garageId'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['garageId']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['garageId']->setValue($document, $return);
            $hydratedData['garageId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['make']) || (! empty($this->class->fieldMappings['make']['nullable']) && array_key_exists('make', $data))) {
            $value = $data['make'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['make']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['make']->setValue($document, $return);
            $hydratedData['make'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['model']) || (! empty($this->class->fieldMappings['model']['nullable']) && array_key_exists('model', $data))) {
            $value = $data['model'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['model']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['model']->setValue($document, $return);
            $hydratedData['model'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['year']) || (! empty($this->class->fieldMappings['year']['nullable']) && array_key_exists('year', $data))) {
            $value = $data['year'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['year']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['year']->setValue($document, $return);
            $hydratedData['year'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['transmission']) || (! empty($this->class->fieldMappings['transmission']['nullable']) && array_key_exists('transmission', $data))) {
            $value = $data['transmission'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['transmission']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['transmission']->setValue($document, $return);
            $hydratedData['transmission'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['driverSide']) || (! empty($this->class->fieldMappings['driverSide']['nullable']) && array_key_exists('driverSide', $data))) {
            $value = $data['driverSide'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['driverSide']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['driverSide']->setValue($document, $return);
            $hydratedData['driverSide'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['wheelDrive']) || (! empty($this->class->fieldMappings['wheelDrive']['nullable']) && array_key_exists('wheelDrive', $data))) {
            $value = $data['wheelDrive'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['wheelDrive']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['wheelDrive']->setValue($document, $return);
            $hydratedData['wheelDrive'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['fuelType']) || (! empty($this->class->fieldMappings['fuelType']['nullable']) && array_key_exists('fuelType', $data))) {
            $value = $data['fuelType'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['fuelType']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['fuelType']->setValue($document, $return);
            $hydratedData['fuelType'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['engineType']) || (! empty($this->class->fieldMappings['engineType']['nullable']) && array_key_exists('engineType', $data))) {
            $value = $data['engineType'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['engineType']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['engineType']->setValue($document, $return);
            $hydratedData['engineType'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['engineCapacity']) || (! empty($this->class->fieldMappings['engineCapacity']['nullable']) && array_key_exists('engineCapacity', $data))) {
            $value = $data['engineCapacity'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['engineCapacity']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['engineCapacity']->setValue($document, $return);
            $hydratedData['engineCapacity'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['color']) || (! empty($this->class->fieldMappings['color']['nullable']) && array_key_exists('color', $data))) {
            $value = $data['color'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['color']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['color']->setValue($document, $return);
            $hydratedData['color'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['kW']) || (! empty($this->class->fieldMappings['kW']['nullable']) && array_key_exists('kW', $data))) {
            $value = $data['kW'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['kW']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['kW']->setValue($document, $return);
            $hydratedData['kW'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['mileage']) || (! empty($this->class->fieldMappings['mileage']['nullable']) && array_key_exists('mileage', $data))) {
            $value = $data['mileage'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['mileage']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['mileage']->setValue($document, $return);
            $hydratedData['mileage'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['features']) || (! empty($this->class->fieldMappings['features']['nullable']) && array_key_exists('features', $data))) {
            $value = $data['features'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['features']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['features']->setValue($document, $return);
            $hydratedData['features'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['owner']) || (! empty($this->class->fieldMappings['owner']['nullable']) && array_key_exists('owner', $data))) {
            $value = $data['owner'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['owner']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['owner']->setValue($document, $return);
            $hydratedData['owner'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['photos']) || (! empty($this->class->fieldMappings['photos']['nullable']) && array_key_exists('photos', $data))) {
            $value = $data['photos'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['photos']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['photos']->setValue($document, $return);
            $hydratedData['photos'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description']) || (! empty($this->class->fieldMappings['description']['nullable']) && array_key_exists('description', $data))) {
            $value = $data['description'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['description']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['price']) || (! empty($this->class->fieldMappings['price']['nullable']) && array_key_exists('price', $data))) {
            $value = $data['price'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['price']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['price']->setValue($document, $return);
            $hydratedData['price'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['currency']) || (! empty($this->class->fieldMappings['currency']['nullable']) && array_key_exists('currency', $data))) {
            $value = $data['currency'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['currency']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['currency']->setValue($document, $return);
            $hydratedData['currency'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['autodealerId']) || (! empty($this->class->fieldMappings['autodealerId']['nullable']) && array_key_exists('autodealerId', $data))) {
            $value = $data['autodealerId'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['autodealerId']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['autodealerId']->setValue($document, $return);
            $hydratedData['autodealerId'] = $return;
        }
        return $hydratedData;
    }
}